<a href="https://colab.research.google.com/github/karthisha-13/AIML_2303A52099/blob/main/lab-01_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1 Implement Basic Data Structures using Numpy, Pandas
 1. Lists
 2. Arrays
 3. Identify their type using type()
 4. Perform mathematical operations on these datasets created- multiplication, division,
 powero
 5. Combine text with Numpy fuction to generate a textual output- Addition of Two:
 array1 +array 2
 6. Implement np.sin(), log(), log2(), np.exp())


In [1]:
import numpy as np
list1=[1,2,3]
array1=np.array(list1)
array1

array([1, 2, 3])

In [2]:
type(list1)

list

In [3]:
type(array1)

numpy.ndarray

In [4]:
list2=[3,4,5]
array2=np.array(list2)
array2

array([3, 4, 5])

In [6]:
print("array2 multiplied by array1:",array1*array2)
print("array2 divided by array1:",array2/array1)
print(print("array2 raised to the power of array1: ",array2**array1))

array2 multiplied by array1: [ 3  8 15]
array2 divided by array1: [3.         2.         1.66666667]
array2 raised to the power of array1:  [  3  16 125]
None


In [8]:
list2=[3,4,5]
array2=np.array(list2)
array2

array([3, 4, 5])

In [9]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)


Adding two numpy arrays {array1} and {array2} together: [4 6 8]


In [10]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [3 4 5] together: [4 6 8]


In [7]:
print("Sine: ",np.sin(array1))
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]
